### ISSUE TITLE
[Issue] KO hardware decode/encode with Gemini lake family

### ISSUE THREAD

**Issue by Jqh63** [intel/media-driver#930]
## Desc: Hardware media decode/encode is KO with iHD driver on Gemini lake family
Unable to perform media decode/encode with iHD_drv_video.so, always have to force use of i965 driver. Impacts are degraded performance and capabilites: no HEVC 10bits for example or high CPU usage. Plus manual configuration is needed, like removal of iHD_drv_video.so or set up LIBVA_DRIVER_NAME to i965

## Current behavior
iHD_drv_video.so generate error message or hangs on Gemini lake processors

## Expected behavior
Working hardware decode as mention into VAAPI and Intel spec for GLK (especially HEVC 10bits HW encode)

## How to reproduce
1. run a Debian/Ubuntu/Alpine (docker or direct host)
2. install intel-media-driver package to get a working VAAPI
3. run a HW encode (plex, handbrake, ...), simple way is a handbrake test with H.265 Intel QSV (docker compose below)
4. CPU/GPU hangs, artifacts into generated files, error messages..
```
[16:42:39] hb_display_init: using VA driver 'iHD'
libva info: VA-API version 1.7.0
libva info: User environment variable requested driver 'iHD'
libva info: Trying to open /opt/intel/mediasdk/lib64/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_7
libva info: va_openDriver() returns 0
[16:42:40] qsv_hevc_make_header: MFXVideoCORE_SyncOperation failed (-17)
[16:42:40] encqsvInit: qsv_hevc_make_header failed
[16:42:40] Failure to initialise thread 'Quick Sync Video encoder (Intel Media SDK)'
```

## Ecosystem
On my test case:
- Asrock j5005 
- running OMV5 (Debian 10)
- with docker and multiple images like LSIO Plex, Handbrake, ...

## Compose
```
version: '2.1'
services:
  handbrake:
    image: jlesage/handbrake
    container_name: handbrake
    environment:
      - USER_ID=1000
      - GROUP_ID=100
      - TZ=Europe/Paris
      #- LIBVA_DRIVER_NAME=i965
    ports:
      - 5800:5800
    volumes:
      - /srv/dev-disk-by-label-data/appdata/handbrake:/config:rw
      - /srv/dev-disk-by-label-media/media:/storage:ro
      - /srv/dev-disk-by-label-media/media/handbrake/watch:/watch:rw
      - /srv/dev-disk-by-label-media/media/handbrake/output:/output:rw
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped
```

## Refs 
[plex forum - tons of users issues](https://forums.plex.tv/t/corrupted-video-output-stream-with-hardware-transcoding/500432/86)
[plex docker image](https://github.com/linuxserver/docker-plex/issues/228)
[maybe related to issue 733](https://github.com/intel/media-driver/issues/733)
